#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-rev HEAD)"

if [ "$branch" = "main" ]; then
    echo "You can not commit to main"
    exit 1
fi

npm run lint
npm run test