name: CD Github Pages

on:
  push:
    branches:
      - develop/*

jobs:
  QA:
    runs-on: ubuntu-latest
    environment:
      name: QA

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

        with:
          node-version: "16"

      - name: Install Dependencies

        run: npm install

      - name: Test coverage

        run: npm run test

  PULL-REQUEST:
    needs: QA
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

      with:
        node-version: "16"

      - name: Get Branch Name
        id: branch-name
        uses: ypicard/get-branch-name-github-action@v1

      - name: pull-request
        run: gh pr create --base main --head ${{ steps.branch-name.outputs.branch }} --title "Pulling ${{ steps.branch-name.outputs.branch }} into main" --body "Pull Requst from actions"

        env:
          GH_TOKEN: ${{ secrets.SECRET_TOKEN }}


