name: CD Github Pages

on:
  push:
    branches:
      - develop/*

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3

        with:
          node-version: "16"

      - name: Install Dependencies

        run: npm install

      - name: Test coverage

        run: npm run test
  pull-request:
    name: Pull Request to Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: repo-sync/pull-request@v3
        with:
          destination_branch: "main"
          pr_title: "Pulling develop into main"
          pr_body: "Automated PR"
          pr_draft: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
